language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install -e .[test]
script:
  - pytest --cov=aiosonic
after_success:
  coveralls
